### ISSUE TITLE
Can't find silhouette, GT depth map (in exr format) and Surface Normal map!

### ISSUE THREAD

**Issue by geokarant** [asafkar/deep_shadow#1]
Dear  Asaf, 

Congrats for your excellent work! I want to reproduce the results, but i get the following  error:

    self.normal_gt = (cv2.cvtColor(cv2.imread(normal_gt_path), cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0) * 2 - 1
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I think it is because it cant find the " *_normal.png". I also think  the silhouette, and the depth maps are missing. Or I am missing something which is so obvious. I appreciate if you can check that files.

Regards!

**Comment by asafkar** [comment]
Hi, 
There was an issue with the uploaded data.
I've uploaded it to the repo itself and fixed the readme.

Please pull the repo to get the files and try again.

Let me know if you encounter any more issues.

Thanks

**Comment by geokarant** [comment]
all files are now there! i am running the code at the moment!  thanks a lot!
