### ISSUE TITLE
Can this repo reconstruct convex/glossy images?

### ISSUE THREAD

**Issue by AminMemariani** [asafkar/deep_shadow#3]
In my case, I want to reconstruct 3D objects from 2D images. The 2d images are captured from convex and glossy objects. Do you think this repo can still be useful in that case?

**Comment by asafkar** [comment]
Hi, 
The code in deep-shadow needs binary shadow maps. 
I suppose you could try training a model to extract shadow maps from glossy objects (assuming it's a simpler problem than predicting a dense depth/normal maps), and from there, run deep-shadow.
You can try achieving this by creating a synthetic dataset which has tuples of glossy objects and their corresponding shadow maps, and then use that to train a model.

I can't ensure this will work, but you can try. If you are able to train a model for the first step, then deep-shadow should work for you.

**Comment by AminMemariani** [comment]
Thank you

**Comment by AminMemariani** [comment]
> Hi, The code in deep-shadow needs binary shadow maps. I suppose you could try training a model to extract shadow maps from glossy objects (assuming it's a simpler problem than predicting a dense depth/normal maps), and from there, run deep-shadow. You can try achieving this by creating a synthetic dataset which has tuples of glossy objects and their corresponding shadow maps, and then use that to train a model.
> 
> I can't ensure this will work, but you can try. If you are able to train a model for the first step, then deep-shadow should work for you.

Thank you
