### ISSUE TITLE
Unable to reconstruct the 3D object

### ISSUE THREAD

**Issue by AminMemariani** [asafkar/deep_shadow#4]
Hi, thank you for the great research you have done.
I ran the train.py for the rose object and I was able to get the "rose_LR=5e-05_dev=mixed" folder which contains the "events" files. However, I am still not able to see the 3D object file. How can I get that?

Thank you

**Comment by asafkar** [comment]
Hi, 
The _"rose_LR=5e-05_dev=mixed"_ directory contains the tensorboard files only.
The NERF-like model is saved in /tmp/deep_shadow/models by default (can be changed by indicating _args.save_dir_.

In order to generate a depth map, which is what this model aims to do, you need to load the model and sample from it using a 2d grid of coordinates. 
Once you generate the depth map, you can generate a 3d object from that, given the camera parameters.

If this isn't clear, I can upload an example in the next few days.

**Comment by AminMemariani** [comment]
> Hi, The _"rose_LR=5e-05_dev=mixed"_ directory contains the tensorboard files only. The NERF-like model is saved in /tmp/deep_shadow/models by default (can be changed by indicating _args.save_dir_.
> 
> In order to generate a depth map, which is what this model aims to do, you need to load the model and sample from it using a 2d grid of coordinates. Once you generate the depth map, you can generate a 3d object from that, given the camera parameters.
> 
> If this isn't clear, I can upload an example in the next few days.

Unfortunately, I am using MacOS and it seems the files are missing in my tmp folder

**Comment by asafkar** [comment]
Can you try indicating a different directory?
Perhaps you don't have write permissions to the /tmp folder

**Comment by AminMemariani** [comment]
> Can you try indicating a different directory? Perhaps you don't have write permissions to the /tmp folder

Sorry for asking a lot. I changed the DIR and executed the train.py again. Now I have a models folder which consists of some .pth files. 
I created a file called load.py

```
import torch
from modelfolder import yourmodel

model = yourmodel()
checkpoint = torch.load('model/rose_LR=5e-05_dev=mixed_1250_snapshot.pth')
try:
    checkpoint.eval()
except AttributeError as error:
    print error
### 'dict' object has no attribute 'eval'

model.load_state_dict(checkpoint['state_dict'])
### now you can evaluate it
model.eval()
```

It seems the model is missing in the repo!
How to see 3D objects?

**Comment by AminMemariani** [comment]
Actually at this step. I just want to know, how the 3D object of rose would look like. Do you have any links so that I can download the object?

**Comment by asafkar** [comment]
Hi,
I've added code to visualize the depth of the trained model and create a 3D ply object from that - 
https://gist.github.com/asafkar/1c2ad8efa80c88097a5216130d3be08c

You can view the ply using a 3d viewer, there are also plugins for vscode that let you view it.

**Comment by AminMemariani** [comment]
> Hi, I've added code to visualize the depth of the trained model and create a 3D ply object from that - https://gist.github.com/asafkar/1c2ad8efa80c88097a5216130d3be08c
> 
> You can view the ply using a 3d viewer, there are also plugins for vscode that let you view it.

Thank you for the valuable work you have done. I forked your gist and added support for those not using CUDA. 
https://gist.github.com/AminMemariani/446b4cba295549410abde00789958abd
